package co.edu.udec.poo.views;

import co.edu.udec.poo.modelos.entidades.User;
import javax.swing.JOptionPane;

/**
 *
 * @author redhood
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        BarraMenu = new javax.swing.JMenuBar();
        menuUsers = new javax.swing.JMenu();
        itemSearchUser = new javax.swing.JMenuItem();
        itemAddUser = new javax.swing.JMenuItem();
        itemEditUser = new javax.swing.JMenuItem();
        itemDeleteUser = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemReportesTodosUsers = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        itemHelp = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Digital");

        menuUsers.setText("Users");

        itemSearchUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/views/icons/icon-busqueda-24.png"))); // NOI18N
        itemSearchUser.setText("Search User");
        itemSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSearchUserActionPerformed(evt);
            }
        });
        menuUsers.add(itemSearchUser);

        itemAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/views/icons/icon-add-24.png"))); // NOI18N
        itemAddUser.setText("Add User");
        itemAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddUserActionPerformed(evt);
            }
        });
        menuUsers.add(itemAddUser);

        itemEditUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/views/icons/icon-editar-24.png"))); // NOI18N
        itemEditUser.setText("Edit User");
        itemEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditUserActionPerformed(evt);
            }
        });
        menuUsers.add(itemEditUser);

        itemDeleteUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/views/icons/icon-basura-24.png"))); // NOI18N
        itemDeleteUser.setText("Delete User");
        itemDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeleteUserActionPerformed(evt);
            }
        });
        menuUsers.add(itemDeleteUser);

        menuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udec/poo/views/icons/icons-reports.png"))); // NOI18N
        menuReportes.setText("Reportes");

        itemReportesTodosUsers.setText("All");
        itemReportesTodosUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReportesTodosUsersActionPerformed(evt);
            }
        });
        menuReportes.add(itemReportesTodosUsers);

        menuUsers.add(menuReportes);

        BarraMenu.add(menuUsers);

        menuHelp.setText("Help");

        itemHelp.setText("About");
        menuHelp.add(itemHelp);

        BarraMenu.add(menuHelp);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddUserActionPerformed
        ViewUsuarios view = new ViewUsuarios(this, true);
        view.setLocationRelativeTo(this);
        view.setVisible(true);
    }//GEN-LAST:event_itemAddUserActionPerformed

    private void itemEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditUserActionPerformed
        itemAddUserActionPerformed(evt);
    }//GEN-LAST:event_itemEditUserActionPerformed


    private void itemReportesTodosUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReportesTodosUsersActionPerformed
        if(User.usersDB == null || User.usersDB.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existen usuarios en el sistema.", "Resultado Negativo", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_itemReportesTodosUsersActionPerformed

    private void menuBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBookActionPerformed

    private void menuLoansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLoansActionPerformed

    private void itemDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeleteUserActionPerformed
        itemAddUserActionPerformed(evt);
    }//GEN-LAST:event_itemDeleteUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem itemAddUser;
    private javax.swing.JMenuItem itemDeleteUser;
    private javax.swing.JMenuItem itemEditUser;
    private javax.swing.JMenuItem itemHelp;
    private javax.swing.JMenuItem itemReportesTodosUsers;
    private javax.swing.JMenuItem itemSearchUser;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUsers;
    // End of variables declaration//GEN-END:variables
}
